sudo: required
services:
  - docker

before_install:
  - docker build -t markshelton/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run markshelton/multi-docker-client-test npm test -- --coverage

after_success:
  - docker build -t markshelton/multi-docker-api ./api
  - docker build -t markshelton/multi-docker-client ./client
  - docker build -t markshelton/multi-docker-proxy ./proxy
  - docker build -t markshelton/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push markshelton/multi-docker-api
  - docker push markshelton/multi-docker-client
  - docker push markshelton/multi-docker-proxy
  - docker push markshelton/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-774239647995
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
